name: testing
on:
  push:
  pull_request:

jobs:
  build:
    name: Build, Lint, and Test with Python ${{ matrix.python-version }}, Django ${{ matrix.django-version }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        django-version: ["3.2", "4.0", "4.1", "4.2"]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Django
        run: pip install Django==${{ matrix.django-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/requirements-testing.txt

      - name: Lint
        run: |
          run python ./manage.py makemigrations --check
          run black --check .
          run isort --check .
          run flake8

      - name: Test
        run: python manage.py test
